- hosts: [$hosts]

  vars:
    is_set:
      # FIXME: allow array in variables
      - btsync_login
      - btsync_password
      - btsync_listening_port
      - btsync_listening_port_webui
      - btsync_listening_address_webui

  tasks:
    - include: ../../common/tasks/is_set.yml

    - get_url: url=http://btsync.s3-website-us-east-1.amazonaws.com/btsync_x64.tar.gz
               dest=/var/cache/ansible/btsync_x64.tar.gz

    - file: path=/opt/btsync owner=root group=root state=directory
    - shell: tar xvz -C /opt/btsync -f /var/cache/ansible/btsync_x64.tar.gz

    # systemd
    - template: src=../files/btsync.service dest=/usr/lib/systemd/system/btsync.service

    - template: src=../files/btsync.conf dest=/etc/btsync.conf owner=root group=root mode=0640
      notify: restart service

    - include: ../../common/tasks/service.yml name=$item state=started
      with_items:
        - btsync

  handlers:
    - include: ../../common/handlers/restart.yml name=$item
      with_items:
        - btsync
