- hosts: [$hosts]

  vars:
    is_set:
      - openvpn_dns
      - openvpn_keys_dir

  tasks:
    - include: ../../common/tasks/is_set.yml

    - pacman: name=openvpn state=installed

    - file: path=/etc/openvpn/keys owner=root group=root state=directory mode=0700

    - template: src=${openvpn_keys_dir}/$item dest=/etc/openvpn/keys/$item
      with_items:
        - ca.crt

    - template: src=${openvpn_keys_dir}/$item dest=/etc/openvpn/keys/$item
      with_items:
        - server.crt
        - server.key
        - dh2048.pem
        - ta.key

    - template: src=../files/$item dest=/etc/openvpn/$item
      with_items:
        - server.conf
      notify:
        - restart openvpn-server

    - action: command systemctl enable openvpn@server
    - service: name=openvpn@server state=started

    # routing
    - sysctl: name=net.ipv4.ip_forward value=1
    - command: ip link set dev eth0 promisc on
    - cron: name="eth0 promisc on" reboot=yes job="ip link set dev eth0 promisc on"

  handlers:
    - name: restart openvpn-server
      action: command systemctl restart openvpn@server
