#!/bin/bash

ufw --force disable
ufw --force reset

ufw default deny

ufw allow 22

ufw allow 80
ufw allow 443

# openvpn
ufw allow 1194

# crashplan
ufw allow 4242

for port in {6881..6891}; do
    ufw allow $port
done

ufw --force enable

iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
