- hosts: [monit, test]

  tasks:
    - pacman: name=monit state=installed

    - service: name=monit state=started
    - action: command systemctl enable monit

    - template: src=../files/monitrc dest=/etc/monitrc mode=0600
      notify: restart monit

    - include: ../../apache/tasks/lif.yml line="Include conf/extra/httpd-monit.conf"

    - template: src=../files/httpd-monit.conf dest=/etc/httpd/conf/extra/httpd-monit.conf
      notify: restart apache
      tags: [ httpd.conf ]

    - file: path=/etc/monit.d state=directory owner=root group=root mode=0700

    - template: src=$item dest=/etc/monit.d/monit-extra.conf
      first_available_file:
        - ../files/monit.d/monit-extra.conf-$inventory_hostname
        - ../files/monit.d/monit-extra.conf-default
      notify: restart monit

  handlers:
    - include: ../../apache/handlers/apache.yml

    - name: restart monit
      action: command systemctl restart monit
      action: command monit monitor all
      ignore_errors: yes
