- hosts: [$hosts]

  tasks:
    - pacman: name=git state=installed

    - user: name=git home=/home/git state=present

    - file: path=$item owner=git group=git state=directory mode=0755
      with_items:
        - /home/git
        - /home/git/.ssh
