- hosts: [$hosts]

  vars:
    is_set:
      - sshd_AllowUsers

  tasks:
    - include: ../../common/tasks/is_set.yml

    - pacman: name=openssh state=installed

    - service: name=sshd state=started
    - action: command systemctl enable sshd

    - template: src=~/.ssh/id_rsa.pub dest=/root/.ssh/$item
      with_items:
        - authorized_keys
        - authorized_keys2

    - template: src=../files/sshd_config dest=/etc/ssh/sshd_config
      notify: restart sshd

  handlers:
    - name: restart sshd
      action: command systemctl restart sshd
