- hosts: [$hosts]

  vars:
    vnstat_php_frontend_version: version-1.5.1
    vnstat_doc_root: /usr/share/webapps/vnstat

  tasks:
    - pacman: name=vnstat state=installed

    - service: name=vnstat state=started
    - action: command systemctl enable vnstat

    - git: repo=https://github.com/bjd/vnstat-php-frontend.git dest=$vnstat_doc_root version=$vnstat_php_frontend_version
    - template: src=../files/config.php dest=$vnstat_doc_root/config.php

    - include: ../../apache/tasks/lif.yml line="Include conf/extra/httpd-vnstat.conf"

    - template: src=../files/httpd-vnstat.conf dest=/etc/httpd/conf/extra/httpd-vnstat.conf
      notify: restart apache
      tags: [ httpd.conf ]

  handlers:
    - include: ../../apache/handlers/apache.yml
