- hosts: [$hosts]

  vars:
    is_set:
      - deluge_pwd_salt
      - deluge_pwd_sha1
      - deluge_localclient_password

  tasks:
    - include: ../../common/tasks/is_set.yml

    - user: name=deluge state=present home=/home/deluge shell=/bin/bash

    - pacman: name=$item state=installed
      with_items:
        - deluge
        - python2-mako

    - file: path=$item owner=deluge group=deluge state=directory mode=0755
      with_items:
        - /home/deluge
        - /home/deluge/downloads/done
        - /home/deluge/downloads/tmp
        - /home/deluge/downloads/torrents
        - /home/deluge/downloads/watch
        - /home/deluge/.config/deluge

    - template: src=../files/$item dest=/home/deluge/.config/deluge/$item
                owner=root group=deluge mode=0640
      with_items:
        - core.conf
        - web.conf
        - auth
      notify:
        - restart deluged
        - restart deluge-web

    - service: name=deluged state=started
    - service: name=deluge-web state=started
    - action: command systemctl enable deluged
    - action: command systemctl enable deluge-web

    - include: ../../apache/tasks/lif.yml line="Include conf/extra/httpd-deluge.conf"

    - template: src=../files/httpd-deluge.conf dest=/etc/httpd/conf/extra/httpd-deluge.conf
      notify: restart apache
      tags: [ httpd.conf ]

  handlers:
    - include: ../../apache/handlers/apache.yml

    - name: restart deluged
      action: command systemctl restart deluged

    - name: restart deluge-web
      action: command systemctl restart deluge-web
