- hosts: [deluge]

  tasks:
    - user: name=deluge state=present home=/home/deluge shell=/bin/bash

    - pacman: name=$item state=installed
      with_items:
        - deluge
        - python2-mako

    - file: path=$item owner=deluge group=deluge state=directory mode=0755
      with_items:
        - /home/deluge
        - /home/deluge/downloads/done
        - /home/deluge/downloads/tmp
        - /home/deluge/downloads/torrents
        - /home/deluge/downloads/watch
        - /home/deluge/.config/deluge

    - template: src=../files/$item dest=/home/deluge/.config/deluge/$item
      with_items:
        - core.conf
        - web.conf
        - auth
      notify: restart deluged
      notify: restart deluge-web

    - service: name=deluged state=started
    - service: name=deluge-web state=started
    - action: command systemctl enable deluged
    - action: command systemctl enable deluge-web

  handlers:
    - name: restart deluged
      action: command systemctl restart deluged
    - name: restart deluge-web
      action: command systemctl restart deluge-web
