- hosts: [owncloud]

  vars:
    owncloud_doc_root: /home/owncloud

  tasks:
    - pacman: name=$item state=installed
      with_items:
        - php-gd
        - php-intl
        - rsync

    - git: repo=https://github.com/owncloud/core dest=$owncloud_doc_root version=$owncloud_version
    - git: repo=https://github.com/owncloud/apps dest=$owncloud_doc_root/apps-git version=$owncloud_version
    - git: repo=https://github.com/owncloud/3rdparty dest=$owncloud_doc_root/3rdparty version=$owncloud_version

    - command: rsync -a $owncloud_doc_root/apps-git/ $owncloud_doc_root/apps

    - file: path=$owncloud_doc_root state=directory owner=http group=http recurse=yes

    - template: src=../files/autoconfig.php dest=$owncloud_doc_root/config/autoconfig.php

    - command: rm $owncloud_doc_root/config/autoconfig.php removes=$owncloud_doc_root/config/config.php

    - name: retrieve passwordsalt from server side config.php
      shell: grep [\"\']passwordsalt[\"\'] $owncloud_doc_root/config/config.php | sed -e "s/[\"\'],.*//g" -e "s/.*[\"\']//g"
             removes=$owncloud_doc_root/config/config.php
      register: owncloud_passwordsalt

    - template: src=../files/config.php dest=$owncloud_doc_root/config/config.php

    - command: rm $owncloud_doc_root/config/config.php removes=$owncloud_doc_root/config/autoconfig.php

    - mysql_user: name=owncloud password=$mysql_owncloud_password priv=owncloud.*:ALL state=present

    - include: ../../apache/tasks/lif.yml line="Include conf/extra/httpd-owncloud.conf"

    - template: src=../files/httpd-owncloud.conf dest=/etc/httpd/conf/extra/httpd-owncloud.conf
      notify: restart apache
      tags: [ httpd.conf ]

  handlers:
    - include: ../../apache/handlers/apache.yml
