- hosts: [$hosts]

  vars:
    is_set:
      - ga_Account
      - ga_DomainName

  tasks:
    - include: ../../common/tasks/is_set.yml

    - command: ln -sf /opt/CrashPlan-install/log /home/owncloud/data/krisoijn/files/crashplan-log
               creates=/home/owncloud/data/krisoijn/files/crashplan-log

    - command: ln -sf /home/deluge/downloads /home/owncloud/data/$item/files/
      with_items:
        - krisoijn

    - file: path=/home/public owner=http group=http state=directory mode=0775

    - include: ../../apache/tasks/lif.yml line="Include conf/extra/httpd-public.conf"

    - template: src=../files/httpd-public.conf dest=/etc/httpd/conf/extra/httpd-public.conf
      notify: restart apache
      tags: [ httpd.conf ]

    - user: name=krisoijn state=present shell=/bin/bash groups=http

    - authorized_key: user=krisoijn key='$FILE(~/.ssh/id_rsa.pub)'

    # public autoindex
    - template: src=../files/autoindex/$item dest=/home/public/$item
      with_items:
        - README.html

  handlers:
    - include: ../../apache/handlers/apache.yml
