- include: base.yml
- include: lamp.yml
- include: web.yml

- hosts: [sigma.krisoijn.com]

  tasks:
    - file: path=/home/owncloud/data/$item/files owner=http group=http state=directory mode=0775
      with_items:
        - krisoijn

    - command: ln -sf /home/deluge/downloads /home/owncloud/data/$item/files/
      with_items:
        - krisoijn

    - file: path=/home/public owner=root group=root state=directory mode=0775

    - include: ../../apache/tasks/lif.yml line="Include conf/extra/httpd-public.conf"

    - template: src=../files/httpd-public.conf dest=/etc/httpd/conf/extra/httpd-public.conf
      notify: restart apache
      tags: [ httpd.conf ]

  handlers:
    - include: ../../apache/handlers/apache.yml
