- include: base.yml
- include: lamp.yml
- include: web.yml

- hosts: [sigma.krisoijn.com]

  tasks:
    - command: ln -sf /home/deluge/downloads /home/owncloud/data/$item/files/deluge
      with_items:
        - krisoijn
